import sys
sys.stdout.reconfigure(encoding="utf-8")

# Read original for frontmatter, scripts, styles only
orig = open(r"D:\workspaces\website\china-trips\src\pages\index.astro", "r", encoding="utf-8").read()
fm_end = orig.index("---", 3) + 3
front = orig[:fm_end]
script_start = orig.index("<script>")
scripts = orig[script_start:]
style_start = orig.index("<style>")
styles = orig[style_start:]

print(f"Extracted frontmatter {len(front)} chars, scripts {len(scripts)} chars, styles {len(styles)} chars")

# Remove the closing </BaseLayout> and </main> from scripts section if present
scripts_clean = scripts.strip()

L = []
def w(s): L.append(s)
def w0(s=""): L.append(s)

# === FRONTMATTER ===
w(front.rstrip())
w0()

# === LAYOUT START ===
w("<BaseLayout")
w('  title={pageTitle}')
w('  description={pageDesc}')
w('  ogImage="/images/hero/og-default.webp"')
w('  schema={scheduleSchema}')
w(">")
w("  <main>")

# === NAVIGATION ===
w('    <nav class="sticky top-0 z-50 bg-[var(--color-bg)]/90 backdrop-blur-md border-b border-[var(--color-border)]">')
w('      <div class="container flex items-center justify-between h-16">')
w('        <a href="/" class="heading-md text-lg">China Trips</a>')
w('        <div class="flex items-center gap-5 text-sm font-medium text-[var(--color-text-secondary)] max-lg:hidden">')
for link in [("Planner","planner"),("Itineraries","itineraries"),("Destinations","destinations"),("Cost","cost"),("Visa","visa"),("FAQ","faq")]:
    w(f'          <a href="#{link[1]}" class="hover:text-[var(--color-text)] transition-colors">{link[0]}</a>')
w("        </div>")
w("      </div>")
w("    </nav>")
w0()

# === HERO ===
w('    <header class="relative min-h-[85dvh] flex items-center overflow-hidden">')
w('      <img src="/images/hero/hero.webp" alt="Great Wall of China panoramic view at golden hour" class="absolute inset-0 w-full h-full object-cover" width="1600" height="900" loading="eager" />')
w('      <div class="absolute inset-0 bg-gradient-to-r from-black/75 via-black/45 to-black/20"></div>')
w('      <div class="container relative py-24 md:py-32">')
w('        <div class="max-w-xl">')
w('          <div class="section-eyebrow text-white/80">Plan Your Journey</div>')
w('          <h1 class="heading-xl text-4xl md:text-5xl lg:text-6xl text-white mb-6">Your China Trip<br/>Starts Here</h1>')
w('          <p class="text-lg md:text-xl max-w-lg mb-10 text-white/75 leading-relaxed">Plan your perfect trip to China with detailed day-by-day itineraries, destination guides with local food and hotel tips, budget tools, visa info, and practical advice \u2014 everything in one page.</p>')
w('          <div class="flex flex-wrap gap-4">')
w('            <a href="#planner" class="btn-primary text-base px-8 py-3.5">Plan My Trip</a>')
w('            <a href="#itineraries" class="btn-secondary !border-white/30 !text-white hover:!border-white text-base px-8 py-3.5">Explore Itineraries</a>')
w("          </div>")
w("        </div>")
w("      </div>")
w('      <div class="scroll-hint"></div>')
w("    </header>")
w0()

# === STAT STRIP ===
w('    <section class="relative z-10 -mt-10 mb-10">')
w('      <div class="container">')
w('        <div class="card-stats stat-banner py-5 px-6 md:px-10 mx-auto max-w-5xl">')
for n, l in [("8","Cities Covered"),("4","Complete Itineraries"),("12","Month Weather Guide"),("54","Countries Visa Info")]:
    w(f'          <div class="stat-item flex-col items-center gap-1 text-center">')
    w(f'            <span class="stat-number">{n}</span>')
    w(f'            <span class="text-sm text-[var(--color-text-secondary)]">{l}</span>')
    w(f'          </div>')
w("        </div>")
w("      </div>")
w("    </section>")

# === BANNER ===
w0()
w('    <section class="border-b border-[var(--color-border)] bg-[var(--color-accent-light)]">')
w('      <div class="container max-w-3xl text-center py-5">')
w('        <p class="body-text text-sm">Independent travel guide \u2014 not a tour agency. All itineraries, prices, and tips are researched and kept current. No affiliate pressure.</p>')
w("      </div>")
w("    </section>")
w0()

# === TRIP PLANNER ===
w('    <section id="planner" class="section-accent-top">')
w('      <div class="container">')
w('        <div class="max-w-3xl mx-auto text-center mb-10 reveal">')
w('          <span class="section-eyebrow">Step 1</span>')
w('          <h2 class="heading-lg text-3xl md:text-4xl text-[var(--color-text)] mb-4">Plan Your China Trip</h2>')
w('          <p class="body-text text-lg">Tell us what you are looking for and we will suggest the best route, destinations, and budget.</p>')
w("        </div>")
w('        <div class="card max-w-2xl mx-auto p-8 reveal reveal-delay-1">')
w('          <form id="trip-planner" class="space-y-6">')
w("            <div>")
w('              <label class="block text-sm font-semibold text-[var(--color-text)] mb-2">How long is your trip?</label>')
w('              <select id="planner-days" class="w-full rounded-lg border border-[var(--color-border)] px-4 py-3 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-[var(--color-accent)] focus:border-transparent">')
w('                <option value="">Select duration</option>')
for d in ["7","10","14","21"]:
    w(f'                <option value="{d}">{d} days</option>')
w("              </select>")
w("            </div>")
w("            <div>")
w('              <label class="block text-sm font-semibold text-[var(--color-text)] mb-2">What interests you?</label>')
w('              <div class="flex flex-wrap gap-2">')
for i in ["History","Food","Nature","Cities","Culture","Adventure"]:
    w(f'                <label class="cursor-pointer"><input type="checkbox" value="{i}" class="peer hidden" data-interest /><span class="inline-block px-4 py-2 rounded-full border border-[var(--color-border)] text-sm peer-checked:bg-[var(--color-accent)] peer-checked:text-white peer-checked:border-[var(--color-accent)] transition-colors">{i}</span></label>')
w("              </div>")
w("            </div>")
w("            <div>")
w('              <label class="block text-sm font-semibold text-[var(--color-text)] mb-2">Who are you traveling with?</label>')
w('              <select id="planner-who" class="w-full rounded-lg border border-[var(--color-border)] px-4 py-3 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-[var(--color-accent)] focus:border-transparent">')
w('                <option value="">Select travel style</option>')
for s in [("solo","Solo"),("couple","Couple"),("family","Family"),("friends","Friends")]:
    w(f'                <option value="{s[0]}">{s[1]}</option>')
w("              </select>")
w("            </div>")
w('            <button type="button" id="planner-submit" class="btn-primary w-full">Get My Recommendation</button>')
w("          </form>")
w('          <div id="planner-result" class="mt-8 hidden">')
w('            <div class="border-t border-[var(--color-border-light)] pt-6">')
w('              <div id="planner-output"></div>')
w("            </div>")
w("          </div>")
w("        </div>")
w("      </div>")
w("    </section>")
w0()

# === ITINERARIES ===
w('    <section id="itineraries" class="section">')
w('      <div class="container">')
w('        <div class="max-w-3xl mb-10 reveal">')
w('          <span class="section-eyebrow">Travel Ideas</span>')
w('          <h2 class="heading-lg text-3xl md:text-4xl text-[var(--color-text)] mb-4">Best China Trip Itineraries</h2>')
w('          <p class="body-text text-lg">Proven routes for every trip length. Each includes day-by-day plans with transport, food, and accommodation. Click to expand.</p>')
w("        </div>")
# Bento-grid: first 2 items take more space
w('        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 stagger-children reveal">')
w("{itineraries.map((itin, i) => (")
w('  <div class={`card p-6 ${i === 0 ? "md:col-span-2 md:grid md:grid-cols-2 md:gap-8" : ""}`}>')
# First featured item has richer layout
w('    {i === 0 && itin.dayPlan && itin.dayPlan.length > 0 ? (')
w('      <>')
w('        <div class="flex flex-col justify-between">')
w('          <div>')
w('            <div class="flex items-center gap-3 mb-3">')
w('              <span class="tag">{itin.days} Days</span>')
w('              <h3 class="heading-md text-xl text-[var(--color-text)]">{itin.name}</h3>')
w("            </div>")
w('            <p class="body-text text-sm mb-1 text-[var(--color-accent)] font-medium">{itin.route}</p>')
w('            <p class="body-text text-sm mb-4">{itin.highlights}</p>')
w('            <div class="flex flex-wrap gap-2 mb-4">')
w('              <span class="tag bg-green-50/70 text-green-700 border-green-200">{itin.bestFor}</span>')
w('              <span class="tag">{itin.estimatedCost}</span>')
w("            </div>")
w("          </div>")
w('          <details class="day-plan-details cursor-pointer">')
w('            <summary class="text-sm font-semibold text-[var(--color-accent)] hover:text-[var(--color-accent-hover)] transition-colors list-none flex items-center gap-1">')
w('              <span>View Day-by-Day Plan ({itin.dayPlan.length} days)</span>')
w('              <span class="summary-arrow text-xs">[+]</span>')
w("            </summary>")
w('            <div class="mt-4 space-y-4 border-t border-[var(--color-border-light)] pt-4">')
w('              {itin.dayPlan.map(d => (')
w('                <div class="pl-3 border-l-2 border-[var(--color-accent-light)]">')
w('                  <div class="flex items-baseline gap-2 mb-1 flex-wrap">')
w('                    <span class="text-xs font-semibold text-[var(--color-accent)] uppercase">Day {d.day}</span>')
w('                    <span class="text-sm font-semibold text-[var(--color-text)]">{d.title}</span>')
w('                    <span class="text-xs text-[var(--color-text-muted)]">{d.city}</span>')
w("                  </div>")
w('                  {d.activities && d.activities.map(a => (')
w('                    <p class="text-sm text-[var(--color-text-secondary)] mb-1"><span class="font-medium text-[var(--color-text)]">{a.label}:</span> {a.detail}</p>')
w("                  ))}")
w('                  <div class="flex flex-wrap gap-x-4 gap-y-1 mt-2 text-xs text-[var(--color-text-muted)]">')
w('                    <span>Stay: {d.stay}</span><span>Go: {d.transport}</span><span>Eat: {d.food}</span>')
w("                  </div>")
w("                </div>")
w("              ))}")
w("            </div>")
w("          </details>")
w("        </div>")
w('        {itin.image ? (')
w('          <div class="img-zoom mt-6 md:mt-0 rounded-xl overflow-hidden h-64">')
w('            <img src={itin.image} alt={itin.name} class="w-full h-full object-cover" />')
w("          </div>")
w("        ) : null}")
w("      </>")
w("    ) : (")
# Regular itinerary items
w("      <>")
w('        <div class="flex items-center gap-3 mb-3">')
w('          <span class="tag">{itin.days} Days</span>')
w('          <h3 class="heading-md text-xl text-[var(--color-text)]">{itin.name}</h3>')
w("        </div>")
w('        <div class="flex flex-wrap gap-2 mb-3">')
w('          <span class="tag bg-green-50/70 text-green-700 border-green-200">{itin.bestFor}</span>')
w('          <span class="tag">{itin.estimatedCost}</span>')
w("        </div>")
w('        <p class="body-text text-sm mb-1 text-[var(--color-accent)] font-medium">{itin.route}</p>')
w('        <p class="body-text text-sm mb-4">{itin.highlights}</p>')
w('        {itin.dayPlan && itin.dayPlan.length > 0 && (')
w('          <details class="day-plan-details group cursor-pointer">')
w('            <summary class="text-sm font-semibold text-[var(--color-accent)] hover:text-[var(--color-accent-hover)] transition-colors list-none flex items-center gap-1">')
w('              <span>View Day-by-Day Plan ({itin.dayPlan.length} days)</span>')
w('              <span class="summary-arrow text-xs">[+]</span>')
w("            </summary>")
w('            <div class="mt-4 space-y-4 border-t border-[var(--color-border-light)] pt-4">')
w('              {itin.dayPlan.map(d => (')
w('                <div class="pl-3 border-l-2 border-[var(--color-accent-light)]">')
w('                  <div class="flex items-baseline gap-2 mb-1 flex-wrap">')
w('                    <span class="text-xs font-semibold text-[var(--color-accent)] uppercase">Day {d.day}</span>')
w('                    <span class="text-sm font-semibold text-[var(--color-text)]">{d.title}</span>')
w('                    <span class="text-xs text-[var(--color-text-muted)]">{d.city}</span>')
w("                  </div>")
w('                  {d.activities && d.activities.map(a => (')
w('                    <p class="text-sm text-[var(--color-text-secondary)] mb-1"><span class="font-medium text-[var(--color-text)]">{a.label}:</span> {a.detail}</p>')
w("                  ))}")
w('                  <div class="flex flex-wrap gap-x-4 gap-y-1 mt-2 text-xs text-[var(--color-text-muted)]">')
w('                    <span>Stay: {d.stay}</span><span>Go: {d.transport}</span><span>Eat: {d.food}</span>')
w("                  </div>")
w("                </div>")
w("              ))}")
w("            </div>")
w("          </details>")
w("        )}")
w("      </>")
w("    )}")
w("  </div>")
w("))}")
w("        </div>")
w("      </div>")
w("    </section>")
w0()

# === DESTINATIONS (unchanged but with enhanced tabs) ===
w('    <section id="destinations" class="section-alt">')
w('      <div class="container">')
w('        <div class="max-w-3xl mb-10 reveal">')
w('          <span class="section-eyebrow">Explore</span>')
w('          <h2 class="heading-lg text-3xl md:text-4xl text-[var(--color-text)] mb-4">Where Should You Go?</h2>')
w('          <p class="body-text text-lg">Explore each destination in depth: day plans, where to stay, what to eat, and how to get there.</p>')
w("        </div>")
w('        <div class="dest-tabs" id="dest-tabs">')
w('          <div class="dest-tab-nav !flex flex-wrap gap-1.5 mb-8 pb-2 overflow-x-auto">')
w('            {destinations.map((d,idx) => (')
w('              <button data-tab={idx} class="dest-tab-btn" class:text-[var(--color-text-secondary)] class:hover:text-[var(--color-text)] class:hover:border-[var(--color-accent)]>{d.name}</button>')
w("            ))}")
w("          </div>")
# Destination panels - keep original content structure
w('          {destinations.map((d,idx) => (')
w('            <div data-tab={idx} class="dest-tab-panel hidden">')
w('              <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">')
w("                <div>")
w('                  <h3 class="heading-md text-2xl text-[var(--color-text)] mb-2">{d.name} <span class="text-lg text-[var(--color-text-muted)]">{d.nameCN}</span></h3>')
w('                  <p class="body-text text-sm mb-4">{d.intro}</p>')
w('                  <div class="flex flex-wrap gap-2 mb-4">')
w('                    <span class="tag">{d.bestFor}</span>')
w('                    <span class="tag">{d.dayCount}</span>')
w('                    <span class="tag">{d.bestTime}</span>')
w("                  </div>")
w('                  {d.dayPlans && d.dayPlans.map(dp => (')
w('                    <details class="mb-4 card p-4 cursor-pointer">')
w('                      <summary class="text-sm font-semibold text-[var(--color-accent)] list-none flex items-center justify-between">')
w('                        <span>{dp.days} Suggested Plan</span>')
w('                        <span class="summary-arrow text-xs">[+]</span>')
w('                      </summary>')
w('                      <div class="mt-3 space-y-3 pt-3 border-t border-[var(--color-border-light)]">')
w('                        {dp.plan && dp.plan.map(p => (')
w('                          <div class="pl-3 border-l-2 border-[var(--color-accent-light)]">')
w('                            <div class="text-xs font-semibold text-[var(--color-accent)] mb-1">{p.label}</div>')
w('                            <div class="text-sm font-medium text-[var(--color-text)] mb-0.5">{p.activity}</div>')
w('                            <div class="text-sm text-[var(--color-text-secondary)]">{p.detail}</div>')
w("                          </div>")
w("                        ))}")
w("                      </div>")
w("                    </details>")
w("                  ))}")
w('                  {d.transit && (')
w('                    <div class="card p-4 mb-4">')
w('                      <h4 class="text-sm font-semibold text-[var(--color-text)] mb-2">Getting There &amp; Around</h4>')
w('                      <p class="body-text text-sm">{d.transit}</p>')
w("                    </div>")
w("                  )}")
w("                </div>")
w("                <div>")
w('                  {d.accommodation && d.accommodation.length>0 && (')
w('                    <div class="card p-4 mb-4">')
w('                      <h4 class="text-sm font-semibold text-[var(--color-text)] mb-3">Where to Stay</h4>')
w('                      <div class="space-y-3">')
w('                        {d.accommodation.map(a => (')
w("                          <div>")
w('                            <div class="flex items-baseline gap-2">')
w('                              <span class="tag">{a.tier}</span>')
w('                              <span class="text-sm font-semibold text-[var(--color-text)]">{a.name}</span>')
w("                            </div>")
w('                            <p class="text-xs text-[var(--color-text-muted)] mt-1">{a.area} &middot; {a.price}</p>')
w("                          </div>")
w("                        ))}")
w("                      </div>")
w("                    </div>")
w("                  )}")
w('                  {d.mustEat && d.mustEat.length>0 && (')
w('                    <div class="card p-4 mb-4">')
w('                      <h4 class="text-sm font-semibold text-[var(--color-text)] mb-3">Must-Try Food</h4>')
w('                      <div class="space-y-3">')
w('                        {d.mustEat.map(m => (')
w("                          <div>")
w('                            <div class="text-sm font-semibold text-[var(--color-text)]">{m.dish}</div>')
w('                            <div class="text-xs text-[var(--color-accent)]">{m.restaurant} ({m.restaurantCN})</div>')
w('                            <div class="text-xs text-[var(--color-text-muted)] mt-0.5">{m.note}</div>')
w("                          </div>")
w("                        ))}")
w("                      </div>")
w("                    </div>")
w("                  )}")
w('                  {d.dayTrips && d.dayTrips.length>0 && (')
w('                    <div class="card p-4">')
w('                      <h4 class="text-sm font-semibold text-[var(--color-text)] mb-3">Nearby Day Trips</h4>')
w('                      <div class="space-y-2">')
w('                        {d.dayTrips.map(dt => (')
w('                          <div class="flex items-start gap-3">')
w('                            <span class="text-xs font-semibold text-[var(--color-text-muted)] w-16 flex-shrink-0">{dt.distance}</span>')
w("                            <div>")
w('                              <div class="text-sm font-medium text-[var(--color-text)]">{dt.name}</div>')
w('                              <div class="text-xs text-[var(--color-text-secondary)]">{dt.highlight}</div>')
w("                            </div>")
w("                          </div>")
w("                        ))}")
w("                      </div>")
w("                    </div>")
w("                  )}")
w("                </div>")
w("              </div>")
w("            </div>")
w("          ))}")
w("        </div>")
w("      </div>")
w("    </section>")
w0()

print(f"Built {len(L)} lines so far...")
print("Writing file...")
with open(r"D:\workspaces\website\china-trips\src\pages\index.astro", "w", encoding="utf-8") as f:
    f.write("\n".join(L))
    f.write("\n\n    <button id=\"back-to-top\" class=\"fixed bottom-6 right-6 z-50 w-11 h-11 rounded-full bg-[var(--color-accent)] text-white shadow-lg opacity-0 invisible transition-all duration-300 hover:bg-[var(--color-accent-hover)] flex items-center justify-center text-xl font-bold pointer-events-none\" aria-label=\"Back to top\">&uarr;</button>\n")
print("Appended BTT button")
