import sys
sys.stdout.reconfigure(encoding="utf-8")
scripts = open(r"D:\workspaces\website\china-trips\_scripts.tmp", "r", encoding="utf-8").read()
out = []
def w(s=""): out.append(s)
w("---")
w('import BaseLayout from "../layouts/BaseLayout.astro";')
w("import {")
w("  destinations, itineraries, faqs, tripTypes, routes,")
w("  visa144hCities, visaPolicyHighlights, monthlyWeather,")
w("  essentialPhrases, transportModes, foodCities,")
w("  alipaySetup, wechatPaySetup")
w('} from "../data/content";')
w("")
w('const pageTitle = "China Trips \u2014 Plan Your Perfect Trip to China | Itineraries, Tips & Tools";')
w('const pageDesc = "Plan your trip to China: detailed day-by-day itineraries, destination guides, budget calculators, visa info, weather tables, and practical advice.";')
w("")
w("const scheduleSchema = {")
w('  "@context": "https://schema.org",')
w('  "@type": "FAQPage",')
w("  mainEntity: faqs.map((f) => ({")
w('    "@type": "Question",')
w("    name: f.question,")
w('    acceptedAnswer: { "@type": "Answer", text: f.answer },')
w("  })),")
w("};")
w("---")
w("")
print(f"Frontmatter: {len(out)} lines")
# Now write to file
with open(r"D:\workspaces\website\china-trips\src\pages\index.astro", "w", encoding="utf-8", newline="") as f:
    for line in out:
        f.write(line + "\r\n")
print("Done writing frontmatter")
