import os, sys
sys.stdout.reconfigure(encoding='utf-8')

PAGES = []

def L(s=""):
    PAGES.append(s)

def astro(expr):
    PAGES.append("{" + expr + "}")

# ===== FRONT MATTER =====
L("---")
L('import BaseLayout from "../layouts/BaseLayout.astro";')
L("import { destinations, itineraries, faqs, tripTypes, routes, visa144hCities, visaPolicyHighlights, monthlyWeather, essentialPhrases, transportModes, foodCities, alipaySetup, wechatPaySetup } from \"../data/content\";")
L("")
L("const pageTitle = \"China Trips \u2014 Plan Your Perfect Trip to China | Itineraries, Tips & Tools\";")
L("const pageDesc = \"Plan your trip to China with detailed day-by-day itineraries, destination guides with accommodation and food tips, budget calculators, visa info, weather guides, and practical travel advice \u2014 everything in one page.\";")
L("")
L("const scheduleSchema = {")
L('  "@context": "https://schema.org",')
L('  "@type": "FAQPage",')
L("  mainEntity: faqs.map(f => ({")
L('    "@type": "Question",')
L("    name: f.question,")
L("    acceptedAnswer: {")
L('      "@type": "Answer",')
L("      text: f.answer,")
L("    },")
L("  })),")
L("};")
L("")
L("const itinerarySchema = {")
L('  "@context": "https://schema.org",')
L('  "@type": "ItemList",')
L("  itemListElement: itineraries.map((itin, i) => ({")
L('    "@type": "ListItem",')
L("    position: i + 1,")
L('    name: itin.name,')
L("    description: `${itin.days}-day itinerary: ${itin.route}. ${itin.highlights}`,")
L("  })),")
L("};")
L("")
L('const destinationSchema = {')
L('  "@context": "https://schema.org",')
L('  "@type": "ItemList",')
L("  itemListElement: destinations.map((d, i) => ({")
L('    "@type": "ListItem",')
L("    position: i + 1,")
L('    name: d.name,')
L("    description: d.intro,")
L("  })),")
L("};")
L("---")
L("")

# ===== LAYOUT OPEN =====
L("<BaseLayout")
L("  title={pageTitle}")
L("  description={pageDesc}")
L('  ogImage="/images/hero/og-default.webp"')
L("  schema={scheduleSchema}")
L(">")
L("  <script type=\"application/ld+json\" set:html={JSON.stringify(itinerarySchema)}></script>")
L('  <script type="application/ld+json" set:html={JSON.stringify(destinationSchema)}></script>')
L("  <main>")

# ===== NAV =====
L("    <nav class=\"sticky top-0 z-50 bg-[var(--color-bg)]/90 backdrop-blur-md border-b border-[var(--color-border)]\">")
L('      <div class="container flex items-center justify-between h-16">')
L('        <a href="/" class="heading-md text-lg">China Trips</a>')
L('        <div class="flex items-center gap-5 text-sm font-medium text-[var(--color-text-secondary)] max-lg:hidden">')
L('          <a href="#planner" class="hover:text-[var(--color-text)] transition-colors">Planner</a>')
L('          <a href="#itineraries" class="hover:text-[var(--color-text)] transition-colors">Itineraries</a>')
L('          <a href="#destinations" class="hover:text-[var(--color-text)] transition-colors">Destinations</a>')
L('          <a href="#cost" class="hover:text-[var(--color-text)] transition-colors">Cost</a>')
L('          <a href="#visa" class="hover:text-[var(--color-text)] transition-colors">Visa</a>')
L('          <a href="#weather" class="hover:text-[var(--color-text)] transition-colors">Weather</a>')
L('          <a href="#faq" class="hover:text-[var(--color-text)] transition-colors">FAQ</a>')
L("        </div>")
L("      </div>")
L("    </nav>")

# ===== HERO =====
L("    <header class=\"relative overflow-hidden\">")
L('      <img src="/images/hero/hero.webp" alt="Great Wall of China panoramic view at golden hour" class="absolute inset-0 w-full h-full object-cover" width="1600" height="900" loading="eager" />')
L('      <div class="absolute inset-0 bg-gradient-to-r from-black/75 via-black/50 to-black/30"></div>')
L('      <div class="container relative pt-24 pb-20 md:pt-28 md:pb-24">')
L('        <div class="max-w-2xl">')
L('          <p class="text-sm font-medium tracking-wider uppercase text-[var(--color-accent-light)] mb-4">Plan Your Journey</p>')
L('          <h1 class="heading-xl text-4xl md:text-5xl lg:text-6xl text-white mb-6">')
L("            Your China Trip Starts Here")
L("          </h1>")
L('          <p class="text-lg md:text-xl max-w-xl mb-8 text-white/80" style="font-family:\'Geist Sans\',sans-serif;line-height:1.65">')
L("            Plan your perfect trip to China with detailed day-by-day itineraries, destination guides with local food and hotel tips, budget tools, visa info, and practical advice \u2014 everything in one page.")
L("          </p>")
L('          <div class="flex flex-wrap gap-4">')
L('            <a href="#planner" class="btn-primary">Plan My Trip</a>')
L('            <a href="#itineraries" class="btn-secondary !border-white/30 !text-white hover:!border-white">Explore Itineraries</a>')
L("          </div>")
L("        </div>")
L("      </div>")
L("    </header>")

# ===== TRIP PLANNER =====
L("    <section id=\"planner\" class=\"section\">")
L('      <div class="container">')
L('        <div class="max-w-3xl mx-auto text-center mb-10">')
L('          <h2 class="heading-lg text-3xl md:text-4xl text-[var(--color-text)] mb-4">Plan Your China Trip</h2>')
L("          <p class=\"body-text text-lg\">Tell us what you're looking for. We'll suggest the best route, cities, and estimated budget.</p>")
L("        </div>")
L('        <div class="card max-w-2xl mx-auto p-8">')
L('          <form id="trip-planner" class="space-y-6">')
L("            <div>")
L('              <label class="block text-sm font-semibold text-[var(--color-text)] mb-2">How long is your trip?</label>')
L('              <select id="planner-days" class="w-full rounded-lg border border-[var(--color-border)] px-4 py-3 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-[var(--color-accent)] focus:border-transparent">')
L('                <option value="">Select duration</option>')
L('                <option value="7">7 days</option>')
L('                <option value="10">10 days</option>')
L('                <option value="14">14 days</option>')
L('                <option value="21">21 days</option>')
L("              </select>")
L("            </div>")
L("            <div>")
L('              <label class="block text-sm font-semibold text-[var(--color-text)] mb-2">What interests you?</label>')
L('              <div class="flex flex-wrap gap-2">')
L("                {[\"History\",\"Food\",\"Nature\",\"Cities\",\"Culture\",\"Adventure\"].map(i => (")
L("                  <label class=\"cursor-pointer\">")
L("                    <input type=\"checkbox\" value={i} class=\"peer hidden\" data-interest />")
L("                    <span class=\"inline-block px-4 py-2 rounded-full border border-[var(--color-border)] text-sm peer-checked:bg-[var(--color-accent)] peer-checked:text-white peer-checked:border-[var(--color-accent)] transition-colors\">{i}</span>")
L("                  </label>")
L("                ))}")
L("              </div>")
L("            </div>")
L("            <div>")
L('              <label class="block text-sm font-semibold text-[var(--color-text)] mb-2">Who are you traveling with?</label>')
L('              <select id="planner-who" class="w-full rounded-lg border border-[var(--color-border)] px-4 py-3 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-[var(--color-accent)] focus:border-transparent">')
L('                <option value="">Select travel style</option>')
L('                <option value="solo">Solo</option>')
L('                <option value="couple">Couple</option>')
L('                <option value="family">Family</option>')
L('                <option value="friends">Friends</option>')
L("              </select>")
L("            </div>")
L('            <button type="button" id="planner-submit" class="btn-primary w-full">Get My Recommendation</button>')
L("          </form>")
L('          <div id="planner-result" class="mt-8 hidden">')
L('            <div class="border-t border-[var(--color-border-light)] pt-6">')
L("              <div id=\"planner-output\"></div>")
L("            </div>")
L("          </div>")
L("        </div>")
L("      </div>")
L("    </section>")

# Write file
code = "\n".join(PAGES)
with open("D:/workspaces/website/china-trips/src/pages/index.astro", "w", encoding="utf-8") as f:
    f.write(code)
print(f"Written {len(code)} chars, {len(PAGES)} lines")
